### DISCUSSION TITLE
Minor version 1.23.0

### DISCUSSION THREAD

**Discussion by mttfranci** [italia/ansc#626] [Announcements]
### Added
  Versione
    - Aggiunta nuova versione 100008

  model_evento.yaml
    - Aggiunti campi nel ModelEvento come segue:
  ```
          operatoreFirmatario:
              type: string
              description: Codice fiscale dell'operatore che ha firmato l'atto.
              example: 'ABCDEF99A11H501A'
            operatoreFirmatarioNome:
              type: string
              description: Nome dell'operatore che ha firmato l'atto.
              example: 'MARIO'
            operatoreFirmatarioCognome:
              type: string
              description: Cognome dell'operatore che ha firmato l'atto.
              example: 'ROSSI'
```

    - Aggiunto campo nel ModelDatiDiNascita come segue: 

```
            tipoNascitaSoggetto: 
                type: string
                description: Identificativo del tipo di nascita del nascituro di cui si sta dichiarando la nascita (decodifica ANSC_107).
                example: '1'  
```
    
    
  Decodifiche
    - Aggiunta decodifica ANSC_107 relativa allo stato di nascita del nascituro
    	
### Fixed   	

  Servizi cooperativi
    - R001: corretto errore nella consultazione degli allegati di un atto redatto da altro comune #549
    - R009: Prenotazione Evento per parti gemellari #571 #611
    - R009: corretto errore Validazione atto Caso d'uso 1311 #580
    - R013: corretta rettifica evento di tipo Annotazione #519
    - R010: corrette annotazioni #508
    - R011: Cancellazione Atto, Eliminazione fisica / annullamento #489
	   
  Trasversale
    - UC 329999: atto di matrimonio religioso da altro comune; campi testimoni resi non obbligatori #569
    - Corretti certificati (art.15) #580
    - Certificati: migliorati i template per differenziare cognome e nome #589
    - CERTIFICAZIONE ATTO DI MORTE CASO D’USO 2101: differenziato lo stato civile de defunto in base al sesso celibe/nubile #597
    - Corretta certificazione impossibile per atto di nascita #602
    - Cittadinanza 52122 - richiesta firma dichiarante impropriamente #576
    - Corretta gestione comuni stranieri nelle certificazioni #592
    - Aggiunta dicitura su anteprima atto per firma digitale del dichiarante #578
    - Corretta gestione Identificativo atto rispetto ad anno atto #599
    - sep_div_004: corretta obbligatorietà allegati #612
    - Trascrizione atto di morte caso d'uso di servizio: aggiunto comparenti non obbligatorio #601
    - trascrizione di una nascita avvenuta all'estero: reso opzionale il campo estremi documento #600
    - Trascrizione atti dall'estero: gestita obbligatorietò allegati in base a richiesta verbale o scritta #594
    - Usecase 1351 Trascrizione provvedimento straniero di adozione (Trascr_018): corretta obbligatorietà metadati #520 #521
			   
  Web Application
    - Corretto errore in annotazione per rettifica di un matrimonio #621
    - Corretta gestione Form.81 - Verbale di giuramento #574
    - Corretta gestione presenza interprete #591
    - Corrette ricerche atti #596
    - Usecase 51107 prestazione di giuramento (con impedimento): eliminata casistica di presenza interessato #550

<hr /><em>This discussion was created from the release <a href='https://github.com/italia/ansc/releases/tag/v1.23.0'>Minor version 1.23.0</a>.</em>
