### ISSUE TITLE
[SC]: modelDatiLingua

### ISSUE THREAD

**Issue by annamaraspin** [italia/ansc#1452]
### Ambiente

pre-produzione

### Servizio

R009 - Servizi cooperativi validazione evento

### idOperazione

assente

### Provenienza segnalazione

Software House

### Comune di riferimento e operatore

anna maraspin

### Descrivi il problema

Buongiorno,
ho delle perplessità sulla riga evidenziata.
1) Annotazioni con riferimento al ModelSoggetto: In questo model sono trattate le persone. I dati di chi devo introdurre?
2) perché ModelSoggetto e non ModelSoggettoML?

![Image](https://github.com/user-attachments/assets/c5aab419-afe3-42ad-ac2b-1dda02c44cca)

### Payload (json)

```JSON

```

**Comment by rvinzani** [comment]
Verifichiamo e le faremo sapere quanto prima

**Comment by mttfranci** [comment]
Salve @annamaraspin , grazie per la segnalazione, in realtà c'è un disallineamento con la documentazione pdf e xlsx, mentre l' OpenAPI riporta il tipo correggo, ovvero array di stringhe : 

https://github.com/italia/ansc/blob/956476039b916581fe1d5dcbf03f219349ddba57/docs/openapi/model_evento.yaml#L3228

Appena possibile provvediamo a correggere anche la versione XLSX e PDF

```yaml
        annotazioni:
          type: array
          items:
            type: string
            description: lista delle annotazioni
```
