### ISSUE TITLE
Rilascio versione 1.9.0 in ambiente di pre produzione

### ISSUE THREAD

**Issue by mttfranci** [italia/ansc#151]
É stata rilasciata in ambiente di preproduzione la versione 1.8.0 di ANSC, sia per quanto riguarda i servizi cooperativi che la web application. Si rimanda al [changelog](https://github.com/italia/ansc/blob/main/docs/Changelog.md) per i dettagli.

Inoltre dal prossimo rilascio verrà introdotto un controllo obbligatorio sul path param di versione, che dovrà coincidere con la Major Version di ANSC (ovvero il primo numero del versionamento semantico, ad esempio al momento la major version è 1)

Prendiamo, a titolo esemplificativo, il servizio di upload : 

```
servers:
  - url: https://anscservicepre.anpr.interno.it/services/service/doc
    description: Servizio di preproduzione
paths:
  /allegato/upload/{version}:
```

Si traduce nella url da invocare: 

```
https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/{version}
```

Dove il parametro 'version' sarà la major versione di ansc, a vale a dire 1 e quindi : 

```
https://anscservicepre.anpr.interno.it/services/service/doc/allegato/upload/1
```
