### ISSUE TITLE
Rilascio versione 1.13.1 in ambiente di pre produzione

### ISSUE THREAD

**Issue by mttfranci** [italia/ansc#373]
É stata rilasciata in ambiente di preproduzione la patch 1.13.1 di ANSC, sia per quanto riguarda i servizi cooperativi che la web application. Si rimanda al [changelog](https://github.com/italia/ansc/blob/main/docs/Changelog.md) per i dettagli.

Inoltre volevamo anticipare che nel prossimo rilascio (presumibilmente intorno al 16 ottobre) verranno rilasciati due interventi : 

# Certificabilità annotazioni contestuali e caso d'uso di servizio

Il nuovo campo sarà : 

```
        flagAnnotazioneNonCertificabile:
          type: boolean
          description: Indica se l'annotazione è certificabile o meno (true=NON CERTIFICABILE, false=CERTIFICABILE)
          example: true
```

# Acquisizione stati di nascita non censiti

```
        idStatoNascita: 
          type: string
          description: ID dello Stato di Nascita
          example: '100' 
        nomeStatoNascita: 
          type: string
          description: Nome dello Stato di Nascita ( Arbitrario se ID='200' altrimenti DENOMINAZIONE della tabella ANPR 02)
          example: 'ITALIA'  
```

Qui trovare il tracciato evento completo come [openapi](https://gist.github.com/mttfranci/bddf21be85b84c078d7d034813dde207) o [zip](https://github.com/italia/ansc/files/12780314/model_evento.zip)
